service:
  update_interval: 10 #Seconds
  log_level: debug

mqtt:
  ## Use mqtts for SSL support
  broker: "mqtt://192.168.7.15:1883"
  user: mqtt
  password: 1q2w3e4r
  client_id: aircac2
  topic_prefix: aircon2
  auto_discovery_topic: homeassistant
  auto_discovery_topic_retain: false


devices:
  - ip: 192.168.7.23
    mac: e81656290425
    name: Jonjon
    port: 80
  - ip: 192.168.7.24
    mac: e8165628c633
    name: Ofir
    port: 80
  - ip: 192.168.7.25
    mac: e81656291b1b
    name: Horim
    port: 80
  